import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryProvider } from "@/providers/QueryProvider";
import { AuthProvider } from "@/components/auth/AuthProvider";
import { NavigationLock } from "@/components/features/attendance/NavigationLock";
import { AdminPasswordModal } from "@/components/features/admin/AdminPasswordModal";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="antialiased">
        <QueryProvider>
          <AuthProvider>
            <NavigationLock />
            {children}
            <AdminPasswordModal />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
